paths:
  /users/:
    post:
      tags:
        - User
      summary: creates a new user
      produces:
      - application/json
      parameters:
      - in: body
        name: sign up
        description: It enables a user to create an account
        schema:
          $ref: '#/definitions/signUp'
      responses:
        201:
          description: An object with user details
  /users/login/:
    post:
      tags:
        - User
      summary: login a user
      produces:
        - application/json
      parameters:
      - in: body
        name: sign in
        description: It enable a user to login into an account
        schema:
          $ref: '#/definitions/login'
      responses:
        200:
          description: Welcome User you are now logged in.
        401:
          description: Username or password does not match.
        403:
          description: User is forbidden from accessing the site
        404:
          description: Username or password does not match.
  /users/reset-password/:
    post:
      tags:
        - User
      summary: reset a user password
      produces:
        - application/json
      parameters:
      - in: body
        name: reset password
        description: It enable a user reset his password
        schema:
          $ref: '#/definitions/resetpassword'
      responses:
        200:
          description: A reset password link has been sent to your email.
        404:
          description: Invalid credentials.
        409:
          description: A reset password link has been sent to this email already.
  /users/change-password/:
    post:
      tags:
        - User
      summary: reset a user password
      produces:
        - application/json
      parameters:

      - in: body
        name: change password
        description: It enable a user change his password
        schema:
          $ref: '#/definitions/change-password'
      responses:
        200:
          description: password has been modified.
        400:
          description: Invalid token sent.
        500:
          description: Your verification link has expired or is invalid
  /users/password/:
    put:
      tags:
        - User
      summary: It updates a users password
      produces:
      - application/json
      parameters:
      - name: authorization
        in: header
        description: Header takes user's token
        type: string
      - in: body
        name: Password update
        description: It enable users to update password
        schema:
          $ref: '#/definitions/updatePassword'
      responses:
        200:
          description: An object with a user profile detail
        401:
          description: Unauthorized request
        400:
          description: Bad request
        409:
          description: Conflict
  /profiles/{username}:
    put:
      tags:
        - Profiles
      summary: It updates a users profile details
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        description: path parameter takes the user's username
        required: true
        type: string
      - name: authorization
        in: header
        description: header takes the user's token
        required: true
        type: string
      - in: body
        name: update user profile
        description: It enables a user update their profile
        required: false
        schema:
          $ref: '#/definitions/updateUserProfile'
      responses:
        200:
          description: An object with a user updated user profile detail
        403:
          description: Unauthorized users
  /profiles/{username}/:
    get:
      tags:
        - Profiles
      summary: It returns a users profile details
      produces:
      - application/json
      parameters:
      - name: username
        in: path
        description: path parameter takes the user's username
        required: true
        type: string
      responses:
        200:
          description: An object with a user profile detail
        404:
          description: User with username not found
  /profiles/:
    get:
      tags:
        - Profiles
      summary: Get all users profile
      produces:
      - application/json
      parameters:
      - in: query
        name: limit
        description: Set the limit for each returned users
      - in: query
        name: page
        description: Set the page for each returned users
      - in: query
        name: order
        description: Set the order for each returned users
      - in: header
        name: authorization
        description: Header takes user authorization token
      responses:
        200:
          description: Success response
        400:
          description: Invalid query parameters
        401:
          description: Unauthorized users
definitions:
  signUp:
    type: object
    properties:
      user:
        type: object
        properties:
          username:
            type: string
          email:
            type: string
          password:
            type: string
          password_confirmation:
            type: string
  login:
    type: object
    properties:
      user:
        type: object
        properties:
          username:
            type: string
          password:
            type: string
  resetpassword:
    type: object
    properties:
      user:
        type: object
        properties:
          email:
            type: string
  change-password:
    type: object
    properties:
      user:
        type: object
        properties:
          password:
            type: string
          password_confirmation:
            type: string
          passwordtoken:
            type: string
  updateUserProfile:
    type: object
    properties:
      user:
        type: object
        properties:
          username:
            type: string
          email:
            type: string
          bio:
            type: string
          image:
            type: string
  updatePassword:
    type: object
    properties:
      oldPassword:
        type: string
      password:
        type: string
      password_confirmation:
        type: string
